# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [1]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

height = np.array(height)
weight = np.array(weight)

bmi = weight / (height**2) * 730

# Print the calculated BMI
print("BMI values:", bmi)

BMI values: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [2]:
import numpy as np

def create_random_matrix(rows, columns, min_value, max_value, dtype="float64"):
    """
    Creates a random matrix with specified parameters.

    Args:
        rows: Number of rows in the matrix.
        columns: Number of columns in the matrix.
        min_value: Minimum value for random numbers in the matrix.
        max_value: Maximum value for random numbers in the matrix.
        dtype: Data type of the matrix (default: "float64").

    Returns:
        A NumPy array representing the random matrix.
    """

    # Validate parameters
    if rows <= 0 or columns <= 0:
        raise ValueError("Rows and columns must be positive integers.")
    if min_value >= max_value:
        raise ValueError("Minimum value must be less than maximum value.")

    # Generate random values within the specified range
    data = np.random.uniform(min_value, max_value, size=(rows, columns))

    # Convert data type if necessary
    if dtype != data.dtype:
        data = data.astype(dtype)

    return data

matrix = create_random_matrix(5, 3, 0, 2, dtype="float")
print(matrix)


[[0.62398848 1.10165273 0.40839057]
 [0.92072537 1.8684977  1.67352932]
 [0.61855927 0.85374998 1.52588199]
 [0.37627879 0.3116001  0.06784056]
 [0.33057259 1.84824308 1.32962797]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [6]:
import csv
import numpy as np
import pandas as pd



In [4]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray




In [7]:
redsox_2017 = 'redsox_2017_hitting.txt'  
redsox_2018 = 'redsox_2018_hitting.txt'  

df_2017 = pd.read_csv(redsox_2017, delimiter=',')  
df_2018 = pd.read_csv(redsox_2018, delimiter=',')  

# Extract SLG column for 2017 and 2018
slg_2017 = df_2017['SLG'].values
slg_2018 = df_2018['SLG'].values

# # Convert SLG values to NumPy arrays
slg_array_2017 = np.array(slg_2017, dtype=float)
slg_array_2018 = np.array(slg_2018, dtype=float)

# Ensures that both SLG arrays have the same length before attempting the subtraction operation. 
# Adjustments are made to trim the longer array to the length of the shorter one.
min_length = min(len(slg_array_2017), len(slg_array_2018))
slg_array_2017 = slg_array_2017[:min_length]
slg_array_2018 = slg_array_2018[:min_length]

# # Perform differential operation
slg_difference = slg_array_2018 - slg_array_2017

# # Display the result
if np.sum(slg_difference) > 0:
    print("2018 was a better year based on SLG.")
elif np.sum(slg_difference) < 0:
    print("2017 was a better year based on SLG.")
else:
    print("No significant difference in SLG between 2017 and 2018.")

2018 was a better year based on SLG.
